# Generated by Django 3.1.5 on 2021-01-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('student_id', models.IntegerField(blank=True, default=0)),
                ('programme_code', models.CharField(blank=True, max_length=6)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('unique', models.CharField(max_length=60)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('class_attended', models.CharField(blank=True, max_length=100)),
                ('lecturer', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
