# Generated by Django 3.1.4 on 2020-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
