# Generated by Django 3.1.4 on 2020-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20201215_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='color',
        ),
        migrations.AddField(
            model_name='participant',
            name='campus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='programme_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='participant',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
