# Generated by Django 3.1.4 on 2020-12-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20201215_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='class_attended',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='lecturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
