# Generated by Django 3.1.5 on 2021-01-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
